=== 4Nightmares/jineta/Vineta.dtd
<!-- DTD-Definition Vineta V3.0 (und aelter) -->

<!ENTITY % Boolean "(ja|nein)">
<!ENTITY % Digit "(0|1|2|3|4|5|6)">
<!ENTITY % FORMATE "(#PCDATA|F|K|U)*">
<!ENTITY % FORMATENZ "(#PCDATA|F|K|U)*">
<!ENTITY % FORMATELN "(#PCDATA|F|K|U|N|L)*">
<!ENTITY % Text "(A)*">

<!-- Formatierungen -->
<!ELEMENT F 	%FORMATE;>	<!-- Fett 		-->
<!ELEMENT K 	%FORMATE;>	<!-- Kursiv 		-->
<!ELEMENT U 	%FORMATE;>  	<!-- Unterstrichen 	-->
<!ELEMENT A	%FORMATENZ;>	<!-- Absatz 		-->
<!ELEMENT L	%FORMATENZ;>	<!-- Liste 		-->

<!-- Zutaten, Zubehoer -->
<!ELEMENT Zutat		%FORMATELN;>
<!ELEMENT Zubehoer	%FORMATELN;>
<!ELEMENT Dekoration	%FORMATELN;>
<!ELEMENT Zutaten (Zutat)+>
<!ELEMENT Zubehoere (Zubehoer)+>
<!ELEMENT Dekorationen (Dekoration)+>
<!ELEMENT BildId (#PCDATA)>

<!-- Cocktail/Rezept -->
<!ELEMENT Name		%FORMATE;>
<!ELEMENT Geschmack	%FORMATE;>
<!ELEMENT Rubrik	%FORMATE;>
<!ELEMENT Wertung       (#PCDATA)> <!-- wg. Kompatibiltaet zu Vineta 1.0, 1.2 -->
<!ELEMENT Anleitung	%Text;>
<!ELEMENT Bemerkung	%Text;>
<!ELEMENT Text		%Text;>

<!-- Um mit den Dateien von Vineta 1.0 and 1.2 kompatibel zu sein,
     sind hier zwei Varianten notwendig: -->
<!ENTITY % BasisEintrag "((Rubrik?, Name) | (Name, Rubrik?))">

<!ENTITY % NurText "(%BasisEintrag;, Text?)">

<!-- Um mit den Datein von Vineta 1.0 and 1.2 kompatibel zu sein,
     benoetigen wir das Element Cocktail: -->
<!ELEMENT Cocktail (%BasisEintrag;, Geschmack?, Wertung?, Zutaten?, Zubehoere?, Dekorationen?, Anleitung?, Bemerkung?)>
  <!ATTLIST Cocktail alkoholhaltig %Boolean; #REQUIRED>

<!ELEMENT Rezept (%BasisEintrag;, Geschmack?, Zutaten?, Zubehoere?, Dekorationen?, Anleitung?, Bemerkung?, BildId?)>
  <!ATTLIST Rezept alkoholhaltig %Boolean; #IMPLIED>
  <!ATTLIST Rezept Wertung %Digit; #IMPLIED>
<!ELEMENT Tip %NurText;>
<!ELEMENT Information %NurText;>

<!-- Um mit den Datein von Vineta 1.0 and 1.2 kompatibel zu sein,
     benoetigen wir das Root-Element Cocktails: -->
<!ELEMENT Cocktails (Cocktail|Tip|Information)*>

<!-- Rezept-Liste (Root) -->
<!ELEMENT Rezepte (Rezept|Tip|Information)*>

<!-- Der Rest der Datei ist fuer die Kompatibiltaet zu Vineta 1.0 and 1.2 Dateien,
     die noch in ISO-8859-1 gespeichert sind -->
<!-- Sonderzeichen -->
<!ENTITY nbsp	"&#160;">
<!ENTITY iexcl	"&#161;">
<!ENTITY cent	"&#162;">
<!ENTITY pound	"&#163;">
<!ENTITY curren	"&#164;">
<!ENTITY yen	"&#165;">
<!ENTITY brvbar	"&#166;">
<!ENTITY sect	"&#167;">
<!ENTITY uml	"&#168;">
<!ENTITY copy	"&#169;">
<!ENTITY ordf	"&#170;">
<!ENTITY laquo	"&#171;">
<!ENTITY not	"&#172;">
<!ENTITY shy	"&#173;">
<!ENTITY reg	"&#174;">
<!ENTITY macr	"&#175;">
<!ENTITY deg	"&#176;">
<!ENTITY plusmn	"&#177;">
<!ENTITY sup2	"&#178;">
<!ENTITY sup3	"&#179;">
<!ENTITY acute	"&#180;">
<!ENTITY micro	"&#181;">
<!ENTITY para	"&#182;">
<!ENTITY middot	"&#183;">
<!ENTITY cedil	"&#184;">
<!ENTITY sup1	"&#185;">
<!ENTITY ordm	"&#186;">
<!ENTITY raquo	"&#187;">
<!ENTITY frac14	"&#188;">
<!ENTITY frac12	"&#189;">
<!ENTITY frac34	"&#190;">
<!ENTITY iquest	"&#191;">

<!-- sprachspezifische Zeichen gross -->
<!ENTITY Agrave	"&#192;">
<!ENTITY Aacute	"&#193;">
<!ENTITY Acirc	"&#194;">
<!ENTITY Atilde	"&#195;">
<!ENTITY Auml 	"&#196;">
<!ENTITY Aring	"&#197;">
<!ENTITY AElig	"&#198;">

<!ENTITY Cedil 	"&#199;">

<!ENTITY Egrave	"&#200;">
<!ENTITY Eacute	"&#201;">
<!ENTITY Ecirc	"&#202;">
<!ENTITY Euml 	"&#203;">

<!ENTITY Igrave	"&#204;">
<!ENTITY Iacute	"&#205;">
<!ENTITY Icirc	"&#206;">
<!ENTITY Iuml 	"&#207;">

<!ENTITY ETH 	"&#208;">

<!ENTITY Ntilde	"&#209;">

<!ENTITY Ograve	"&#210;">
<!ENTITY Oacute	"&#211;">
<!ENTITY Ocirc	"&#212;">
<!ENTITY Otilde	"&#213;">
<!ENTITY Ouml 	"&#214;">

<!ENTITY times 	"&#215;">

<!ENTITY Oslash	"&#216;">

<!ENTITY Ugrave	"&#217;">
<!ENTITY Uacute	"&#218;">
<!ENTITY Ucirc	"&#219;">
<!ENTITY Uuml 	"&#220;">

<!ENTITY Yacute	"&#221;">

<!ENTITY THORN	"&#222;">

<!-- sprachspezifische Zeichen klein -->
<!ENTITY szlig 	"&#223;">

<!ENTITY agrave	"&#224;">
<!ENTITY aacute	"&#225;">
<!ENTITY acirc 	"&#226;">
<!ENTITY azilde	"&#227;">
<!ENTITY auml 	"&#228;">
<!ENTITY aring 	"&#229;">
<!ENTITY aelig 	"&#230;">

<!ENTITY ccedil	"&#231;">

<!ENTITY egrave	"&#232;">
<!ENTITY eacute	"&#233;">
<!ENTITY ecirc	"&#234;">
<!ENTITY euml	"&#235;">

<!ENTITY igrave	"&#236;">
<!ENTITY iacute	"&#237;">
<!ENTITY icirc	"&#238;">
<!ENTITY iuml	"&#239;">
<!ENTITY ieth	"&#240;">

<!ENTITY ntilde	"&#241;">

<!ENTITY ograve	"&#242;">
<!ENTITY oacute	"&#243;">
<!ENTITY ocirc 	"&#244;">
<!ENTITY ozilde	"&#245;">
<!ENTITY ouml 	"&#246;">

<!ENTITY divide	"&#247;">

<!ENTITY oslash	"&#248;">

<!ENTITY ugrave	"&#249;">
<!ENTITY uacute	"&#250;">
<!ENTITY ucirc	"&#251;">
<!ENTITY uuml 	"&#252;">

<!ENTITY yacute	"&#253;">

<!ENTITY thorn	"&#254;">

<!ENTITY yuml	"&#255;">

=== 4Nightmares/jineta/Tester.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
#filetype:	Vineta Recipe Database
#version:	3.0
-->
<!DOCTYPE Rezepte SYSTEM "Vineta.dtd">
<Rezepte>
 <Rezept>
  <Name>Tester</Name>
  <Zutaten>
   <Zutat>&lt;L&gt;1 ml Mililiter</Zutat>
   <Zutat>1,5 l Liter</Zutat>
   <Zutat>2.5 cm Zentimeter</Zutat>
   <Zutat>1/2 Stück</Zutat>
   <Zutat>2 1/3 Stück</Zutat>
   <Zutat>¾ Äpfel</Zutat>
   <Zutat>1¼ l Wasser</Zutat>
   <Zutat>7½ Orangenschalenraspel&lt;/L&gt;</Zutat>
  </Zutaten>
  <Bemerkung>
   <A>&lt;F&gt;für 12 Personen&lt;/F&gt;</A>
  </Bemerkung>
 </Rezept>

 <Rezept>
  <Name>Tester 2</Name>
  <Zutaten>
   <Zutat>1 ml Mililiter</Zutat>
   <Zutat>1,5 l Liter</Zutat>
   <Zutat>2.5 cm Zentimeter</Zutat>
   <Zutat>1/2 Stück</Zutat>
   <Zutat>2 1/3 Stück</Zutat>
   <Zutat>¾ Äpfel</Zutat>
   <Zutat>1¼ l Wasser</Zutat>
   <Zutat>7½ Orangenschalenraspel</Zutat>
  </Zutaten>
  <Bemerkung>
   <A>Yield: 4 Servings</A>
  </Bemerkung>
 </Rezept>

 <Rezept Wertung="6">
  <Name>Was kann jineta?</Name>
  <Rubrik>Fähigkeiten</Rubrik>
  <Geschmack>Fühlt sich gut an!</Geschmack>
  <Zutaten>
   <Zutat>&lt;L&gt;Ein super Programm&lt;/L&gt;</Zutat>
  </Zutaten>
  <Zubehoere>
   <Zubehoer>&lt;L&gt;Maus</Zubehoer>
   <Zubehoer>Tastatur</Zubehoer>
   <Zubehoer>Bildschirm&lt;/L&gt;</Zubehoer>
  </Zubehoere>
  <Dekorationen>
   <Dekoration>&lt;L&gt;Ein modernes Windows&lt;/L&gt;</Dekoration>
  </Dekorationen>
  <Anleitung>
   <A>Absatz 1: ohne jegliche Formatierung wirkt das Ganze ein wenig langweilig...</A>
   <A>Absatz 2: Deshalb gibt es &lt;F&gt;&lt;K&gt;Di&lt;/F&gt;nge&lt;/K&gt; wie &lt;F&gt;Fettschrift&lt;/F&gt;, &lt;K&gt;Kursivschrift&lt;/K&gt; und &lt;U&gt;Unterstreichen&lt;/U&gt;. Das geht auch &lt;F&gt;&lt;K&gt;&lt;U&gt;zusammen&lt;/U&gt;&lt;/K&gt;&lt;/F&gt;.</A>
   <A>Oder wie wäre es mit einer Liste?</A>
   <A>&lt;L&gt;Listeintrag</A>
   <A>Listeintrag</A>
   <A>&lt;/L&gt;</A>
   <A>Oder vielleicht sogar eine automatische Numerierung?</A>
   <A>&lt;N&gt;Listeintrag</A>
   <A>Listeintrag&lt;/N&gt;</A>
  </Anleitung>
  <Bemerkung>
   <A>Die aktuelle Version ist immer unter</A>
   <A>&lt;F&gt;KLICK &gt;&gt;&lt;/F&gt; http://www.tusche-welt.de/jineta.html &lt;F&gt;&lt;&lt; KLICK&lt;/F&gt;</A>
   <A>zu finden.</A>
   <A>Bei Fragen, die die Hilfe nicht beantwortet, stehen wir Ihnen unter</A>
   <A>&lt;F&gt;KLICK &gt;&gt;&lt;/F&gt; mailto:jineta@tusche-welt.de &lt;F&gt;&lt;&lt; KLICK&lt;/F&gt;</A>
   <A>zur Verfügung.</A>
   <A>Absatz 1: ohne jegliche Formatierung wirkt das Ganze ein wenig langweilig...</A>
   <A>Absatz 2: Deshalb gibt es Dinge wie &lt;F&gt;Fettschrift&lt;/F&gt;, &lt;K&gt;Kursivschrift&lt;/K&gt; und &lt;U&gt;Unterstreichen&lt;/U&gt;. Das geht auch &lt;F&gt;&lt;K&gt;&lt;U&gt;zusammen&lt;/U&gt;&lt;/K&gt;&lt;/F&gt;.</A>
   <A>Oder wie wäre es mit einer Liste?</A>
   <A>&lt;L&gt;Listeintrag</A>
   <A>Listeintrag</A>
   <A>&lt;/L&gt;</A>
   <A>Oder vielleicht sogar eine automatische Numerierung?</A>
   <A>&lt;N&gt;Listeintrag</A>
   <A>Listeintrag</A>
   <A>&lt;/N&gt;</A>
   <A>Absatz 1: ohne jegliche Formatierung wirkt das Ganze ein wenig langweilig...</A>
   <A>Absatz 2: Deshalb gibt es Dinge wie &lt;F&gt;Fettschrift&lt;/F&gt;, &lt;K&gt;Kursivschrift&lt;/K&gt; und &lt;U&gt;Unterstreichen&lt;/U&gt;. Das geht auch &lt;F&gt;&lt;K&gt;&lt;U&gt;zusammen&lt;/U&gt;&lt;/K&gt;&lt;/F&gt;.</A>
   <A>Oder wie wäre es mit einer Liste?</A>
   <A>&lt;L&gt;Listeintrag</A>
   <A>Listeintrag</A>
   <A>&lt;/L&gt;</A>
   <A>Oder vielleicht sogar eine automatische Numerierung?</A>
   <A>&lt;N&gt;Listeintrag</A>
   <A>Listeintrag</A>
   <A>&lt;/N&gt;</A>
   <A>Absatz 1: ohne jegliche Formatierung wirkt das Ganze ein wenig langweilig...</A>
   <A>Absatz 2: Deshalb gibt es Dinge wie &lt;F&gt;Fettschrift&lt;/F&gt;, &lt;K&gt;Kursivschrift&lt;/K&gt; und &lt;U&gt;Unterstreichen&lt;/U&gt;. Das geht auch &lt;F&gt;&lt;K&gt;&lt;U&gt;zusammen&lt;/U&gt;&lt;/K&gt;&lt;/F&gt;.</A>
   <A>Oder wie wäre es mit einer Liste?</A>
   <A>&lt;L&gt;Listeintrag</A>
   <A>Listeintrag</A>
   <A>&lt;/L&gt;</A>
   <A>Oder vielleicht sogar eine automatische Numerierung?</A>
   <A>&lt;N&gt;Listeintrag</A>
   <A>Listeintrag&lt;/N&gt;</A>
  </Bemerkung>
 </Rezept>

</Rezepte>
